service: otp-lambda-app

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_HOST: your-db-host
    DB_USER: your-user
    DB_PASS: your-password
    DB_NAME: otp_db
    DB_PORT: 3306
    ENV: lambda

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node18
    platform: node
    concurrency: 10